### PR TITLE
Tweak versioning and return back failing on CI

### PR DESCRIPTION
**Pull request by bocharsky-bw**
A possible fix for: https://github.com/symfony/demo/pull/994#issuecomment-499892242

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Hm, still does not work, probably the problem is in something else, depends on how that "hash" is generated, because when I manually change the full path to the repo locally - it still works for me. Closing it

**Comment by javiereguiluz** [comment]
@bocharsky-bw would this be fixed (or would it simplify the solution) if we disable versioning? I think we can do that for this demo app.

**Comment by bocharsky-bw** [comment]
Hm, if we could consider disabling versioning on this app - I think it might help then. Let's figure it out

**Comment by bocharsky-bw** [comment]
OK, this looks like a working example based on TravisCI

**Comment by bocharsky-bw** [comment]
I think this one is ready

**Comment by javiereguiluz** [comment]
Thanks Victor for working on this feature, this is much appreciated.

**Pull request merged**
