### PR TITLE
Fix Doctrine fixtures service auto-configuration

### PR DESCRIPTION
**Pull request by yceruto**
I've missed this during the update to DoctrineFixturesBundle 3.0

### CODE REVIEW

**Comment by phpeek** [comment]
@yceruto I guess that my PR is no longer relevant - https://github.com/symfony/demo/pull/724

**Comment by yceruto** [comment]
@phpeek Oops, I don't see your PR, I should have commented on your PR instead, sorry for that.

**Comment by phpeek** [comment]
No worries.

**Comment by yceruto** [comment]
closing in favor of https://github.com/symfony/demo/pull/727

**Pull request closed without merging**
