### PR TITLE
php8: fixed named arguments order

### PR DESCRIPTION
**Pull request by COil**
This is to fix:

Capture d’écran 2023-02-14 à 22 25 44

### CODE REVIEW

**Comment by derrabus** [comment]
There's nothing to fix here. That PhpStorm inspection is pointless and disabling it gives me peace of mind in every codebase I've worked on so far. 😌

**Review by OskarStark — APPROVED** [review]

**Comment by COil** [comment]
> There's nothing to fix here. That PhpStorm inspection is pointless and disabling it gives me peace of mind in every codebase I've worked on so far. 😌

Yes, but it's mainly for consistency to avoid having different orders everywhere. It should/could be a php-cs-fixer rule.

**Comment by OskarStark** [comment]
You are right from a technical POV @derrabus, but I would argue that most of the devs write it in the from @COil proposed order anyway. That said I am +1 to merge this change.

This repo ist mostly for newcomers 🤷🏼‍♂️

**Review by jderusse — APPROVED** [review]
For enforcing consistency

**Comment by javiereguiluz** [comment]
I agree with all of you ... but there seems to be more people in favor of merging this, so let's do it. Thanks Loïc!

**Pull request merged**
