### PR TITLE
[CI] Use ramsey/composer-install

### PR DESCRIPTION
**Pull request by rosier**
~~Running `composer update` changes composer.lock~~

Use ramsey/composer-install to cache and install the composer dependencies

### CODE REVIEW

**Comment by stof** [comment]
what should be done instead is running `composer install`. We don't want to run an update in that CI job, as we are committing the lock file.

**Comment by jkufner** [comment]
`composer install && npm ci` is the correct way to do things in CI. However, running `composer validate` can be considered as running a test, which is a good idea too.

**Comment by stof** [comment]
but that's the whole point. With your change moving it higher, other linters won't run anymore if the composer.json reports any warning. The validation should stay in the part of the steps being about running tests rather than going into the setup part.

**Comment by rosier** [comment]
I moved `composer validate` up because I don't know why `composer update` was used instead of `composer install`. 

I agree with using `composer install` and like to propose using the action ramsey/composer-install for that.

**Comment by javiereguiluz** [comment]
I'd prefer to minimize the third-party actions we use ... if `composer update` is wrong in our CI update, could we just replace it by `composer install`? Thanks

**Comment by javiereguiluz** [comment]
Jan, thanks for improving this ... and thanks to your patience during the review process

**Comment by rosier** [comment]
No worries

**Pull request merged**
