### PR TITLE
cleanup: use final classes

### PR DESCRIPTION
**Pull request by COil**
Hello, these classes could be `final` right? (except the entities)

(just done one example, will do the other if it is OK)

### CODE REVIEW

**Comment by derrabus** [comment]
In my apps, I usually declare all classes `final` unless I have a good reason not to. I wouldn't mind if the demo app followed this rule as well. 🙂

So 👍🏻  from my side.

**Comment by COil** [comment]
The only problem I see is that the maker bundle doesn't put the final keyword on controllers.

**Review by OskarStark — APPROVED** [review]
> The only problem I see is that the maker bundle doesn't put the final keyword on controllers.

@weaverryan should we use final for controllers in maker bundle?

**Comment by GromNaN** [comment]
There are [good reasons](https://matthiasnoback.nl/2018/09/final-classes-by-default-why/) to use final by default. Can we explain with a comment somewhere is this project?

**Comment by javiereguiluz** [comment]
This practice is very common in Symfony apps, so let's merge this. Thanks Loïc!

**Comment by jrushlow** [comment]
> > The only problem I see is that the maker bundle doesn't put the final keyword on controllers.
> 
> @weaverryan should we use final for controllers in maker bundle?

@OskarStark https://github.com/symfony/maker-bundle/pull/1539

**Pull request merged**
