### PR TITLE
Update lock and skip project ID registration on Travis

### PR DESCRIPTION
**Pull request by yceruto**
Fix https://github.com/symfony/demo/pull/691 with https://github.com/symfony/demo/pull/691#issuecomment-342175350.

This should fix the tests on master.

### CODE REVIEW

**Comment by stof** [comment]
you should also update the CONTRIBUTING.md with a warning about having to skip registration when working on this project

**Comment by javiereguiluz** [comment]
Just asking: what if we define a Flex ID for this project after all? That'd be wrong in a real project (each user must have their own ID) but as @fabpot said, this is a very special project. Moreover, using the same ID would allow us to get stats about the usage of this project. What do you think?

**Comment by stof** [comment]
@javiereguiluz should each *user* actually have a flex id, or each project ? If it has to be a different id per user, storing it into the composer.json is plain wrong in Flex, as the composer.json is not per user but per project.

**Comment by javiereguiluz** [comment]
@stof yes, the ID is a "user ID", not a "project ID". However, and only for this particular and so special project, we could bend this rule and "hardcode" the ID so every user that clones/downloads this project uses the same ID.

Advantages:

* This PR and all the other mentioned problems disappear.
* We could use this ID to gather (anonymous and very generic) stats about the usage of this project.

**Comment by stof** [comment]
if the id is a user id, the architecture of Flex is broken: it cannot store it in the project-level composer.json file.

**Comment by stof** [comment]
@javiereguiluz  the PR https://github.com/symfony/demo/pull/691 is saying `project id`, so it looks like you and @fabpot are not agreeing on what the id is about.

**Comment by javiereguiluz** [comment]
If I'm wrong (probably I am!!) then this problem solved itself: the ID is per project; this is a project; we can set up a project ID and avoid all issues.

**Comment by yceruto** [comment]
> project ID should be different per project

As far as I understand in https://github.com/symfony/demo/pull/691 "project ID" == "user project ID" I guess we're talking about the same thing :/

**Comment by fabpot** [comment]
The ID is indeed a **project** ID as there is no notion of users in Flex.

If this project is **never** used as a basis for new projects, then having a hardcoded id is fine. What I fear is people using this as a base for their new projects and so inheriting the ID.

**Comment by javiereguiluz** [comment]
Let's close this because the Flex ID is a project ID not a user ID, so it's OK to leave it. Fabien is right about developers using this for their project, but we always said that this is a demo project, not a real project.

**Pull request closed without merging**
