### PR TITLE
Fix compat with Composer 2 by using composer/package-versions-deprecated instead of ocramius/package-versions

### PR DESCRIPTION
**Pull request by nicolas-grekas**
As suggested by composer 2 when trying to upgrade deps.

### CODE REVIEW

**Comment by gmponos** [comment]
Fixes https://github.com/symfony/demo/issues/1127

**Comment by nicolas-grekas** [comment]
Might be fixed with a simple composer up if these PRs are accepted:
- https://github.com/doctrine/migrations/pull/999
- https://github.com/doctrine/dbal/pull/4084
- https://github.com/doctrine/orm/pull/8184

**Comment by gmponos** [comment]
All the above are merged.. so do we close this and wait for the above packages to be tagged?

**Comment by javiereguiluz** [comment]
Let's merge this now so it's ready for everybody ... and in the next update we'll install the other dependencies with the needed changes. Thanks Nicolas!

**Pull request merged**
