### PR TITLE
Add Symfony and Doctrine PHPStan extensions

### LINKED ISSUE #1379: PHPStan - Symfony + Doctrine
It would be interesting to add [Symfony extension for PHPStan](https://github.com/phpstan/phpstan-symfony) and [Doctrine extensions for PHPStan](https://github.com/phpstan/phpstan-doctrine).

### PR DESCRIPTION
**Pull request by ker0x**
Fix #1379

### CODE REVIEW

**Comment by seb-jean** [comment]
Should the `phpstan-baseline.neon` file be regenerated with the new errors?

**Comment by ker0x** [comment]
> Should the `phpstan-baseline.neon` file be regenerated with the new errors?

I regenerated it, but nothing has changed with these new modifications

**Comment by seb-jean** [comment]
Sorry ;).

I think it should be added to the `phpstan.neon.dist` file:
```yaml
parameters:
    doctrine:
        objectManagerLoader: tests/object-manager.php
```
https://github.com/phpstan/phpstan-doctrine#configuration

**Comment by javiereguiluz** [comment]
I love it! Thanks for contributing this Romain!

**Pull request merged**
