### PR TITLE
Albanian translation

### PR DESCRIPTION
**Pull request by llupa**
Albanian XLIFF language files added, and config.yml updated.

### CODE REVIEW

**Comment by llupa** [comment]
Note: This is very fresh. I opened the PR in Draft so I can re-read it in the next days. 

- I have checked and adapted language so it is also not breaking UI elements. 
- Language used is in informal tone like it is in `ita` since formal Albanian gives a fake vibe. 

Tools used: 
- https://fjalorthi.com/zgjedho for verb conjugation
- http://www.seelrc.org:8080/albdict/ to detect barbarisms
- Albanian - German dictionary ISBN 9783468053955

PS. I am Albanian

**Comment by llupa** [comment]
waiting for possible convention acceptance at https://github.com/symfony/symfony/pull/53797

**Comment by javiereguiluz** [comment]
I see that the linked PR was merged. Does that mean that this PR is also mergeable? Thanks

**Comment by llupa** [comment]
I will update tonight with the same conventions and add the translator notes!

**Comment by llupa** [comment]
@javiereguiluz _este PR es listo_

**Comment by javiereguiluz** [comment]
This is now merged!

@llupa what a great contribution you did here! Your meticulous work to make sure that the translation was as good as possible is truly inspiring. We're fortunate to have you in our community.

**Pull request merged**
