### PR TITLE
Add MakerBundle as a dev dependency

### PR DESCRIPTION
**Pull request by bocharsky-bw**
What about to add a maker bundle to this Demo distribution? I think a lot of people are using Demo for some testing, bug reproducing, etc. and have to install it maker bandle themselves - it would be cool to have it installed already. Also, I think it's good to reveal Maker bundle to newcomers as well.

### CODE REVIEW

**Comment by javiereguiluz** [comment]
Thinking about this ... what if we make it a real dependency, instead of a "dev" dependency? MakerBundle is great and having installed in Symfony Demo would be a great way to showcase it.

**Comment by bocharsky-bw** [comment]
Hm, but what's the point of using it in prod? I just don't want to make devs think that it's a good idea to use MakerBundle in prod environment

**Comment by javiereguiluz** [comment]
Yes, you are right! It wasn't a very smart suggestion 😅

**Comment by javiereguiluz** [comment]
Merged! Thanks.

**Pull request merged**
