### PR TITLE
Updated the front-end dependencies

### PR DESCRIPTION
**Pull request by javiereguiluz**

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
We also need to run `yarn install && yarn build` and commit changes here

**Comment by javiereguiluz** [comment]
I did that ... don't you see a lot of CSS and JS files here? https://github.com/symfony/demo/pull/990/files  I see 38 files created/deleted.

**Comment by bocharsky-bw** [comment]
I still see uncommitted changes locally after running `yarn build`:

Screen Shot 2019-06-03 at 18 05 18

**Comment by javiereguiluz** [comment]
Victor, please run these commands locally and check if you see anything different. Thanks!

```bash
$ git checkout master && git fetch upstream && git merge upstream/master && yarn install && yarn encore production

Already on 'master'
Your branch is up to date with 'upstream/master'.
Already up to date.
yarn install v1.16.0
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.87s.
yarn run v1.16.0
$ /Users/javier/work/symfony-demo/node_modules/.bin/encore production
Running webpack ...

 DONE  Compiled successfully in 6354ms                                                                                                                                                              5:15:36 PM

 I  38 files written to public/build
Entrypoint app [big] = runtime.26bd8744.js 0.2375624d.js 1.734a5257.js app.9f402dd6.css app.94e6145a.js
Entrypoint login = runtime.26bd8744.js 0.2375624d.js login.897801f7.js
Entrypoint admin [big] = runtime.26bd8744.js 0.2375624d.js 2.665337b4.js admin.5cc2ebf1.css admin.74750e33.js
Entrypoint search = runtime.26bd8744.js 0.2375624d.js 1.734a5257.js search.b34d41ab.js
✨  Done in 8.17s.
```

```bash
$ git status

On branch master
Your branch is up to date with 'upstream/master'.

nothing to commit, working tree clean
```

**Comment by bocharsky-bw** [comment]
@javiereguiluz Hm, yes, I do! Here's my output:
```
$ git checkout master && git fetch origin  && git merge origin/master && yarn install && yarn encore production
$ git status

On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    public/build/2.665337b4.js
	modified:   public/build/entrypoints.json
	modified:   public/build/manifest.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	public/build/2.63838593.js

no changes added to commit (use "git add" and/or "git commit -a")
```

But I used `origin` instead, I don't have `upstream`

**Pull request closed without merging**
