### PR TITLE
Add yarn instructions

### PR DESCRIPTION
**Pull request by Irtoson**
Proposition to update README in order to add yarn instructions (needed if you want some CSS on your page ;) )

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Symfony Demo has committed public/build/ dir which mean you don't have to run those commands locally, it will just work out of the box for you

**Comment by Irtoson** [comment]
I agree, it should work, but unfortunately, did not work for me. I encountered some errors using Chrome 110.0.5481.104 on Windows 11 :
image
Issues https://github.com/symfony/demo/issues/1263 and https://github.com/symfony/demo/issues/1272 mention it, I thought we could add this quick "fix" to the instructions ?

**Comment by COil** [comment]
> Symfony Demo has committed public/build/ dir which mean you don't have to run those commands locally, it will just work out of the box for you

Yes, but the project car be forked and used to create an actual blog. So, knowing how to regenerate the assets is useful (doc is always useful).

**Comment by wouterj** [comment]
> I agree, it should work, but unfortunately, did not work for me. I encountered some errors using Chrome 110.0.5481.104 on Windows 11 :

Content-Security-Policy errors aren't fixed by regenerating the assets. Also, the Symfony demo application doesn't come with a Content-Security-Policy header so you must have configured something (on your local web server or in the application) that causes that error.

> Yes, but the project car be forked and used to create an actual blog. So, knowing how to regenerate the assets is useful (doc is always useful).

I would say that this is not the purpose of the README of this project. Adding more details might only confuse newcomers for what is necessary to run this project. The README already refers to the official docs and the Fast Track book, both of which document using yarn/npm when working with CSS/JS.

**Comment by javiereguiluz** [comment]
@Irtoson thanks for this proposal. However, we're going to close this as "won't fix" for the reasons explained in the above comments.

It's important that this application works fully without having to install or configure anything. Adding those instructions in the READM could be confusing about the need to run those commands.

In addition to being used as a self-learning tool, this app is used in workshops, to benchmark Symfony, by the core PHP team to test new features, etc. That's why we need to be careful about adding things like this. I hope you understand it.

**Pull request closed without merging**
