### PR TITLE
replaced external $_SERVER variable with filter_input

### PR DESCRIPTION
**Pull request by francescobianco**
It is just a micro fix, I hope it can be considered a small improvement towards the use of this standard.

### CODE REVIEW

**Comment by stof** [comment]
-1 for that. There is no reason to make the front controller diverge from the official recipe.

**Comment by francescobianco** [comment]
@stof sorry for hurting you, is there something bad on usage of filter_input?

**Comment by stof** [comment]
Well, using `filter_input` without any filter provides no value.

And this repo is the demo project. Making its `index.php` diverge from what gets created by default for a Symfony project does not make any sense, and would rather create confusion when newcomers compare the demo to their newly created project..

**Comment by GrahamCampbell** [comment]
This PR looks like spam.

**Pull request closed without merging**
